- name: Setup Monitoring Stack
  hosts: monitoring
  become: yes

  tasks:

    - name: Install packages
      apt:
        name:
          - docker.io
          - docker-compose
          - python3
          - python3-pip
        update_cache: yes

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes
            
    - name: Create webhook directory
      file:
        path: /opt/webhook
        state: directory
    
    - name: Copy webhook
      copy:
        src: webhook/
        dest: /opt/webhook/    
        

    - name: Copy monitoring stack
      copy:
        src: ../../docker/
        dest: /opt/monitoring/

        
    - name: Run docker compose
      shell: |
        cd /opt/monitoring
        docker-compose up -d
