version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

  webhook:
    image: python:3.10
    container_name: webhook
    working_dir: /app
    volumes:
      - /opt/webhook:/app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    env_file:
      - /opt/monitoring/.env
