version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

  webhook:
    build: ../webhook
    ports:
      - "5000:5000"
