[webservers]
{{ hostvars[inventory_hostname]['instance_public_ips'][0] }} ansible_user={{ hostvars[inventory_hostname]['ssh_user'] }} ansible_ssh_private_key_file=~/.ssh/id_rsa
{{ hostvars[inventory_hostname]['instance_public_ips'][1] }} ansible_user={{ hostvars[inventory_hostname]['ssh_user'] }} ansible_ssh_private_key_file=~/.ssh/id_rsa

[haproxies]
{{ hostvars[inventory_hostname]['instance_public_ips'][0] }} ansible_user={{ hostvars[inventory_hostname]['ssh_user'] }} ansible_ssh_private_key_file=~/.ssh/id_rsa
{{ hostvars[inventory_hostname]['instance_public_ips'][1] }} ansible_user={{ hostvars[inventory_hostname]['ssh_user'] }} ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
# These will be populated by the GitHub Actions workflow
# project_id = ""
# region = ""
# zone = ""
# ssh_public_key = ""
# ssh_private_key = ""
