name: Monitoring Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Get VM IP
        run: echo "USE terraform output or gcloud here"

      - name: Run Ansible
        run: |
          ansible-playbook -i inventory.ini playbooks/setup.yml
